name: meedu
description: A simple State Managment, Dependency Injection, Reactive programming for dart Projects.
version: 0.5.0
homepage: https://github.com/darwin-morocho/flutter-meedu

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  test: ^1.14.6
  equatable: ^1.2.5
  get: ^3.23.1
