name: meedu
description: A simple State Managment, Dependency Injection, Reactive programming for dart Projects.
version: 0.5.2+2
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter:
  #   sdk: flutter
  coverage: ^0.14.1
  test: ^1.14.6
  equatable: ^1.2.5
  pedantic: ^1.9.0
  # get: ^3.23.1
