name: meedu
description: A simple State Managment, Dependency Injection, Reactive programming and Navigation for Flutter apps.
version: 0.4.0+1
homepage: https://github.com/darwin-morocho/flutter-meedu

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^1.2.5
  get:
